# see http://www.appveyor.com/docs/appveyor-yml

##### ENABLE REMOVE RDP ACCESS #####
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#######################

#---------------------------------#
#      build configuration        #
#---------------------------------#
build_script:
 - cmd: 'msbuild .\.build\smartsheet-csharp-sdk.msbuild /p:TheVersion="%APPVEYOR_BUILD_VERSION%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

#---------------------------------#
#       tests configuration       #
#---------------------------------#
#environment:
  #TODO: PUT ENVIRONMENT VARS HERE

# TODO: Get the mock API running using a before_test entry as described at https://www.appveyor.com/docs/running-tests/
#test:
#  assemblies:
#    - .\.deploy\TestSDKMockAPI.dll

artifacts:
- path: '.deploy\nuget-package\*.nupkg'
- path: '.deploy\*.zip'

deploy:
  - provider: GitHub # See https://www.appveyor.com/docs/deployment/github/
    release: v$(APPVEYOR_BUILD_VERSION)
    description: 'Appveyor deployed v$(APPVEYOR_BUILD_VERSION)'
    auth_token:
      secure: TODO_TODO+TODO_TODO # encrypted token from https://github.com/settings/tokens
    artifact: /(.*\.nupkg)|(.*\.zip)/ # upload NuGet & zip files to release assets
    draft: false
    prerelease: false
    on:
      branch: master                  # only deploy on master
      appveyor_repo_tag: true         # only deploy when there is a tag pushed
      appveyor_repo_tag_name: publish # only deploy when tag == "publish"
  
  - provider: NuGet # See https://www.appveyor.com/docs/deployment/nuget/
    api_key:
      secure: TODO_TODO+TODO_TODO # GET API KEY FROM NUGET
    artifact: /.*\.nupkg/
    on:
      branch: master                  # only deploy on master
      appveyor_repo_tag: true         # only deploy when there is a tag pushed
      appveyor_repo_tag_name: publish # only deploy when tag == "publish"

##### KEEP RDP ACCESS #####
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#######################
