//    #[license]
//    SmartsheetClient SDK for C#
//    %%
//    Copyright (C) 2014 SmartsheetClient
//    %%
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//        
//            http://www.apache.org/licenses/LICENSE-2.0
//        
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//    %[license]

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Smartsheet.Api.Models
{
    /// <summary>
    /// Represents the webhook shared secret. </summary>
    /// <seealso href="http://smartsheet-platform.github.io/api-docs/#sharedsecret-object">SharedSecret Object Help</seealso>
    public class WebhookSharedSecret
    {
        /// <summary>
        /// Shared secret for this webhook, randomly generated by Smartsheet. Read-only. 
        /// See Authenticating Callbacks for details about how this value can be used.
        /// </summary>
        private string sharedSecret;

        /// <summary>
        /// Get the Shared secret for this webhook, randomly generated by Smartsheet.
        /// </summary>
        /// <returns> the shared secret </returns>
        public string SharedSecret
        {
            get { return sharedSecret; }
            set { this.sharedSecret = value; }
        }
    }
}
